export const getTableData = [
  {
    user: {
      id: "uNknkbkdbdfkmlsamlsd",
      name: "Danili Sousa1",
      email: "danilo@gmail.com",
      time: "a minute ago",
      price: 500,
      userImage: "/images/course.jpg",
      appImage: "/images/chat/c1.jpg",
      balance: 4000,
      offersCompleted: 0,
      coinsEarned: 0,
      referralEarnings: 0,
      referrer: "DollahBot",
      usersReferred: 0,
      status: true,
    },
    time: "a minute ago",
    reward: 500,
    remark: "offer",
  },
  {
    user: {
      id: "uNknkbkdbdfkmlsamlsd",
      name: "Danili Sousa2",
      email: "danilo@gmail.com",
      time: "a minute ago",
      price: 500,
      userImage: "/images/course.jpg",
      appImage: "/images/chat/c1.jpg",
      balance: 4000,
      offersCompleted: 0,
      coinsEarned: 0,
      referralEarnings: 0,
      referrer: "DollahBot",
      usersReferred: 0,
      status: true,
    },
    time: "a minute ago",
    reward: 500,
    remark: "withdrawal",
  },
  {
    user: {
      id: "uNknkbkdbdfkmlsamlsd",
      name: "Danili Sousa3",
      email: "danilo@gmail.com",
      time: "a minute ago",
      price: 500,
      userImage: "/images/course.jpg",
      appImage: "/images/chat/c1.jpg",
      balance: 4000,
      offersCompleted: 0,
      coinsEarned: 0,
      referralEarnings: 0,
      referrer: "DollahBot",
      usersReferred: 0,
      status: true,
    },
    time: "a minute ago",
    reward: 500,
    remark: "offer",
  },
  {
    user: {
      id: "uNknkbkdbdfkmlsamlsd",
      name: "Danili Sousa4",
      email: "danilo@gmail.com",
      time: "a minute ago",
      price: 500,
      userImage: "/images/course.jpg",
      appImage: "/images/chat/c1.jpg",
      balance: 4000,
      offersCompleted: 0,
      coinsEarned: 0,
      referralEarnings: 0,
      referrer: "DollahBot",
      usersReferred: 0,
      status: true,
    },
    time: "a minute ago",
    reward: 500,
    remark: "withdrawal",
  },
  {
    user: {
      id: "uNknkbkdbdfkmlsamlsd",
      name: "Danili Sousa5",
      email: "danilo@gmail.com",
      time: "a minute ago",
      price: 500,
      userImage: "/images/course.jpg",
      appImage: "/images/chat/c1.jpg",
      balance: 4000,
      offersCompleted: 0,
      coinsEarned: 0,
      referralEarnings: 0,
      referrer: "DollahBot",
      usersReferred: 0,
      status: true,
    },
    time: "a minute ago",
    reward: 500,
    remark: "offer",
  },
];
